### ISSUE TITLE
App crash in ViewPhotosActivity

### ISSUE THREAD

**Issue by zedlabs** [named-data-mobile/ndn-photo-app#107]
app crashes when i try to open any image received

Log--
2019-03-12 21:16:49.746 20385-20385/memphis.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: memphis.myapplication, PID: 20385
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at memphis.myapplication.ViewPhotosActivity$1.onTick(ViewPhotosActivity.java:56)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:130)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jrandallclark** [comment]
This is something I discovered as well. It seems to be caused when images are sent back-to-back and have the same filename. The code needs to be rewritten to handle this.

**Comment by jrandallclark** [comment]
Does this happen when you have only sent a single picture?

**Comment by zedlabs** [comment]
yes, this happens on one device and on the other device first it would not even open the camera, i fixed that (#96 ), but  it still crashes in the newContentActivity

**Comment by dev-ritik** [comment]
I faced the exact same bug in **one** of my devices. Upon debugging I found that `onTick` method gets executed more than the number of photos present in the ArrayList.
To be more precise I had a single image in the list, so the maximum time was 5050 milisec but it got called twice when it had 5036 and 32 `millisUntilFinished`. So the error says,

`java.lang.IndexOutOfBoundsException: Index: 1, Size: 1`

**Comment by zedlabs** [comment]
@dev-ritik was it working fine on other devices? If so what android version were they running on?

**Comment by dev-ritik** [comment]
Yes, its working fine on the other one(Android 7.0) but the bug appears in the device running Android 8.1.

**Comment by jrandallclark** [comment]
There are some unresolved issues with Android 8.1 (See https://redmine.named-data.net/issues/4747). 

@zedlabs What version of Android were you using?

**Comment by zedlabs** [comment]
9.0 @jrandallclark

**Comment by zedlabs** [comment]
@jrandallclark i think this PR would fix this issue around the different Android versions.
