### ISSUE TITLE
App crash on sharing image through camera

### ISSUE THREAD

**Issue by zedlabs** [named-data-mobile/ndn-photo-app#85]
android version: android 6.0.1
api : 23

app crashes due to inability to decode the bitmap captured, i am working on it

**Comment by jrandallclark** [comment]
Could you post the stack trace? Android 6.0.1 is the only version we have tested extensively so far. What device are you using as well?

**Comment by zedlabs** [comment]
i was testing with a onePlus one, It worked fine when i tried it with the Mi A2(android : 9.0)

crash started here--

03-07 22:41:25.104 31836-31836/memphis.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: memphis.myapplication, PID: 31836
    Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:com.cyngn.hexo, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo, com.android.systemui.navbar=overlay:com.cyngn.hexo}
    java.lang.OutOfMemoryError: Failed to allocate a 51916812 byte allocation with 16773904 free bytes and 47MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
        at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
        at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
        at memphis.myapplication.MainActivity.onActivityResult(MainActivity.java:432)
        at android.app.Activity.dispatchActivityResult(Activity.java:6456)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3729)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3776)
        at android.app.ActivityThread.-wrap16(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
